### ISSUE TITLE
Vue 3 and Vite implementation example

### ISSUE THREAD

**Issue by RobbyBourne1** [mongodb-js/charts-embed-sdk#56] opened 2022-01-04 15:20 UTC
Hi I was wondering if we could get some documentation around implementing this sdk into a vue application that is using vite. I am currently experiencing some problems around the bson package that the sdk is using. It doesn't seem related but this error doesn't pop up until I try to use the Embedded SDK in the project. 

![image](https://user-images.githubusercontent.com/27830572/148078986-9d21d907-28f2-4312-b83e-0b0068e08650.png)

I have been banging my head on this issue for the last day or so. So further documentation would be really helpful. 

the solution I found was adding this snippet into the index.html file
`  <script>
    const global = globalThis;
  </script>`

Thanks in advance for your help

**Comment by shaketbaby** [comment] 2022-01-04 23:19
Thanks @RobbyBourne1 for reporting. There is a bug in the version of `bson` used by Charts embedding SDK which causes this issue. This bug has been fixed in the latest version of `bson`. We are going to release a new version of SDK soon, likely next month, which will fix this issue. In the interim, you can keep your current solution and remove it after we release the new version. Sorry about the inconveniences.

**Comment by shaketbaby** [comment] 2022-02-22 00:49
@RobbyBourne1 we have just released v2.2.0, would you please be able to check if the issue has been fixed? Thanks!

**Comment by abhay-agarwal** [comment] 2022-03-06 06:28
I am using this with Nuxt 3 (a framework based on Vue 3 + Vite) and I do not receive this error.

**Comment by shaketbaby** [comment] 2022-03-06 22:33
Sorry to hear @abhay-agarwal , may I ask what version of SDK are you using? Is it the latest `v2.2.0`?

**Comment by shaketbaby** [comment] 2022-03-06 22:36
Sorry @abhay-agarwal , ignore my previous comment, I read it wrong. Glad to know that it's working.

**Comment by kristinamongo** [comment] 2023-12-28 04:55
Closing this as it's not a bug but a feature request.

I've posted the idea for a Vue 3 example to the MDB Charts Feature Request page to get more visibility and upvotes - you can find it [here](https://feedback.mongodb.com/forums/923524-charts/suggestions/47600888-provide-a-vue-3-implementation-example-of-an-embed).

**Closed by kristinamongo** 2023-12-28 04:55 UTC
