### ISSUE TITLE
Query all available dashboards or charts

### ISSUE THREAD

**Issue by AlexRoosWork** [mongodb-js/charts-embed-sdk#88] opened 2023-09-12 11:37 UTC
We are creating dashboards and charts, but are wondering if you always need to manually copy paste the ChartIDs or DashboardIDs. It would be very nice to query all available dashboards given a `baseURL`

Something like `sdk.getDashboardIds()` or `sdk.getChartIds({dashboardId})` would be very nice.

**Comment by kristinamongo** [comment] 2023-09-13 04:28
Hi @AlexRoosWork, thank you for the feedback. We do have `getAllCharts()` for embedded dashboards. This returns an array of chart instances that include `chartId`. Here is an [example app](https://github.com/mongodb-js/charts-embed-sdk/tree/2f940473788a28c9450f736d2ac3d40b39e19894/examples/dashboard/unauthenticated-get-chart) using this method.

There is currently no method for getting all dashboards for a `baseURL` but I would highly recommend that you add this to the [MDB Charts feedback page](https://feedback.mongodb.com/forums/923524-charts) to get more visibility and upvotes. We usually plan our work around the most requested features.

**Comment by kristinamongo** [comment] 2023-12-28 03:47
Thanks for submitting a feature request! 
Closing this for now as it's not a bug but a feature request.

If anyone would like to upvote the idea, it's [here](https://feedback.mongodb.com/forums/923524-charts/suggestions/47239976-query-all-dashboards).

**Closed by kristinamongo** 2023-12-28 03:47 UTC
Labels: enhancement
